export let lista_nomes = ['acre', 'alagoas', 'amapá', 'amazonas', 'bahia', 'ceará', 'distrito federal', 'espírito santo', 'goiás', 'maranhão', 'mato grosso', 'mato grosso do sul', 'minas gerais', 'pará', 'paraíba', 'paraná', 'pernambuco', 'piauí', 'rio de janeiro', 'rio grande do norte', 'rio grande do sul', 'rondônia', 'roraima', 'santa catarina', 'são paulo', 'sergipe', 'tocatins']

export let lista_paisagens = ["url('./imagens/ac.jpg')", "url('./imagens/al.jpg')", "url('./imagens/ap.jfif')", "url('./imagens/am.jpg')", "url('./imagens/ba.jpg')", "url('./imagens/ce.jpg')", "url('./imagens/df.jpg')", "url('./imagens/es.jpg')", "url('./imagens/go.jpeg')", "url('./imagens/ma.jpg')", "url('./imagens/mt.jpg')", "url('./imagens/ms.jpg')", "url('./imagens/mg.jpg')", "url('./imagens/pa.jpg')", "url('./imagens/pb.jpg')", "url('./imagens/pr.jpg')", "url('./imagens/pe.jpg')", "url('./imagens/pi.jpeg')", "url('./imagens/rj.jpeg')", "url('./imagens/rn.jpg')", "url('./imagens/rs.jpg')", "url('./imagens/ro.jpg')", "url('./imagens/rr.jpg')", "url('./imagens/sc.jpeg')", "url('./imagens/sp.jpg')", "url('./imagens/se.jpg')", "url('./imagens/to.jpg')"]

export let lista_regioes = ['Norte', 'Nordeste', 'Norte', 'Norte', 'Nordeste', 'Nordeste', 'Centro Oeste', 'Sudeste', 'Centro Oeste', 'Nordeste', 'Centro Oeste', 'Centro Oeste', 'Sudeste', 'Norte', 'Nordeste', 'Sul', 'Nordeste', 'Nordeste', 'Sudeste', 'Nordeste', 'Sul', 'Norte', 'Norte', 'Sul', 'Sudeste', 'Nordeste', 'Norte']

export let lista_capital = ['rio branco', 'maceió', 'macapá', 'manaus', 'salvador', 'fortaleza', 'brasília', 'vitória', 'goiânia', 'são luís', 'cuiabá', 'campo grande', 'belo horizonte', 'belém', 'joão pessoa', 'curitiba', 'recife', 'teresina', 'rio de janeiro', 'natal', 'porto alegre', 'porto velho', 'boa vista', 'florianópolis', 'são paulo', 'aracaju', 'palmas']
 
export let lista_populacao = ['906.876', '3.365.351', '877.613', '4.269.995', '14.985.284', '9.240.580', '3.094.325', '4.108.508', '7.206.589', '7.153.262', '3.567.234', '2.839.188', '21.411.923', '8.77.124', '4.059.905', '11.597.484', '9.674.793', '3.289.290', '17.463.349', '3.560.903', '11.466.630', '1.815.278', '625.713', '7.338.473', '46.649.132', '2.338.474', '1.607.363']

export let lista_mapa = ["url('./mapa/ac.png')", "url('./mapa/al.png')", "url('./mapa/ap.png')", "url('./mapa/am.png')", "url('./mapa/ba.png')", "url('./mapa/ce.png')", "url('./mapa/df.png')", "url('./mapa/es.png')", "url('./mapa/go.png')","url('./mapa/ma.png')", "url('./mapa/mt.png')", "url('./mapa/ms.png')", "url('./mapa/mg.png')", "url('./mapa/pa.png')", "url('./mapa/pb.png')", "url('./mapa/pr.png')", "url('./mapa/pe.png')", "url('./mapa/pi.png')", "url('./mapa/rj.png')", "url('./mapa/rn.png')", "url('./mapa/rs.png')", "url('./mapa/ro.png')", "url('./mapa/rr.png')", "url('./mapa/sc.png')", "url('./mapa/sp.png')", "url('./mapa/se.png')", "url('./mapa/to.png')"]

export let lista_bandeiras = ["url('./bandeiras/ac.jpg')", "url('./bandeiras/al.jpg')", "url('./bandeiras/ap.jfif')", "url('./bandeiras/am.jpg')", "url('./bandeiras/ba.jpg')", "url('./bandeiras/ce.jpg')", "url('./bandeiras/df.jpg')", "url('./bandeiras/es.jpg')", "url('./bandeiras/go.jpeg')", "url('./bandeiras/ma.png')", "url('./bandeiras/mt.jpg')", "url('./bandeiras/ms.jpg')", "url('./bandeiras/mg.jpg')", "url('./bandeiras/pa.jpg')", "url('./bandeiras/pb.jpg')", "url('./bandeiras/pr.jpg')", "url('./bandeiras/pe.jpg')", "url('./bandeiras/pi.jpeg')", "url('./bandeiras/rj.jpeg')", "url('./bandeiras/rn.jpg')", "url('./bandeiras/rs.jpg')", "url('./bandeiras/ro.jpg')", "url('./bandeiras/rr.jpg')", "url('./bandeiras/sc.jpeg')", "url('./bandeiras/sp.jpg')", "url('./bandeiras/se.jpg')", "url('./bandeiras/to.jpg')"]